"""Telling a parent (base) config apart from a per-device config.

Parent templates are not shipped with this add-on and are not copied anywhere.
They are the base firmware files already sitting in the ESPHome directory --
the ones you flashed the batch from. That means parents and the per-device
configs generated from them share a directory, so the add-on has to classify
every file it finds.

The rule, most explicit first:

1. A file carrying our own generated header is a **child**. We wrote it.
2. ``# x-template: false`` forces **child**; ``# x-template: true`` (or any
   ``# x-match-*`` directive) forces **parent**.
3. A file whose ``esphome.name`` contains a ``${mac}`` placeholder, or which
   sets ``name_add_mac_suffix: true``, is a **parent**. This is the signal that
   needs no setup: it is exactly the MAC-suffix logic the add-on exists to
   resolve, and a per-device config never has it, because generation strips it.
4. Anything else is a **child** (an ordinary device config, or a package).

Both :class:`~app.templates.TemplateRepository` and
:class:`~app.config_store.EsphomeConfigStore` classify through this module, so
"what counts as a parent" is defined exactly once. That matters for safety as
much as for tidiness: the store refuses to write over a parent, and it can only
do that if it agrees with the repository about which files those are.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

from . import yaml_compat as yc

_LOGGER = logging.getLogger(__name__)

#: Prepended to every file this add-on generates. Its presence proves the file
#: is a generated child, never a hand-authored parent.
GENERATED_MARKER = "# Generated by ESPHome Device Scan"

#: `# x-key: value`, case-insensitive, tolerant of spacing.
DIRECTIVE_RE = re.compile(r"^\s*#\s*x-([a-z-]+)\s*:\s*(.+?)\s*$", re.IGNORECASE)

#: Directives are read only from the header block -- the run of comments and
#: blank lines before the first real YAML key -- so an `# x-...` string buried
#: deep inside a config cannot silently change how it is classified.
HEADER_LIMIT = 60

#: Substitution names that stand for the device's MAC in a base config.
MAC_PLACEHOLDER_RE = re.compile(
    r"\$\{\s*(mac|mac_suffix|macaddr|mac_address)\s*\}|\$(mac|mac_suffix|macaddr|mac_address)\b",
    re.IGNORECASE,
)

TRUTHY = frozenset({"true", "yes", "on", "1"})
FALSEY = frozenset({"false", "no", "off", "0"})


@dataclass(frozen=True)
class Classification:
    """Why a file was judged a parent or not."""

    is_parent: bool
    #: generated-header / directive / mac-placeholder / mac-suffix-flag / default
    reason: str
    #: Header directives, lowercased keys, for the caller to interpret further.
    directives: dict[str, str]
    #: Literal part of ``esphome.name`` before a MAC placeholder, when present.
    #: ``cloudbay-t-${mac}`` yields ``cloudbay-t``. This is the implicit prefix.
    name_prefix: str | None = None


def read_header_directives(raw: str) -> dict[str, str]:
    """Parse ``# x-key: value`` lines from a file's leading comment block."""
    directives: dict[str, str] = {}
    for line in raw.splitlines()[:HEADER_LIMIT]:
        stripped = line.strip()
        if not stripped:
            continue
        if not stripped.startswith("#"):
            break  # first real YAML content ends the header block
        match = DIRECTIVE_RE.match(line)
        if match:
            directives[match.group(1).lower()] = match.group(2).strip()
    return directives


def is_generated(raw: str) -> bool:
    """Whether this add-on wrote the file."""
    return raw.lstrip().startswith(GENERATED_MARKER)


def derive_name_prefix(declared_name: str) -> str | None:
    """The stable part of a base config's name, before its MAC placeholder.

    ``cloudbay-t-${mac}`` -> ``cloudbay-t``. This is what makes a parent match
    its children without any directive: the file already says which family it
    belongs to, so there is nothing for the user to configure.
    """
    match = MAC_PLACEHOLDER_RE.search(declared_name)
    if match is None:
        return None
    prefix = declared_name[: match.start()].rstrip("-_ ")
    return prefix or None


def classify(raw: str, path: Path | None = None) -> Classification:
    """Decide whether ``raw`` is a parent template. Never raises."""
    directives = read_header_directives(raw)

    if is_generated(raw):
        return Classification(False, "generated-header", directives)

    marker = directives.get("template", "").strip().lower()
    if marker in FALSEY:
        return Classification(False, "directive", directives)
    has_match_directive = any(key.startswith("match-") for key in directives)
    if marker in TRUTHY or has_match_directive:
        return Classification(
            True, "directive", directives, _name_prefix_of(raw, path)
        )

    # Auto-detection: MAC-suffix logic is the tell.
    try:
        root = yc.compose(raw)
    except yc.YamlParseError as err:
        if path is not None:
            _LOGGER.debug("Cannot classify %s: %s", path.name, err)
        return Classification(False, "unparseable", directives)
    if root is None:
        return Classification(False, "empty", directives)

    esphome = yc.map_get(root, "esphome")
    if esphome is None:
        return Classification(False, "no-esphome-block", directives)

    name_node = yc.map_get(esphome, "name")
    declared = getattr(name_node, "value", None)
    if isinstance(declared, str) and MAC_PLACEHOLDER_RE.search(declared):
        return Classification(
            True, "mac-placeholder", directives, derive_name_prefix(declared)
        )

    suffix_node = yc.map_get(esphome, "name_add_mac_suffix")
    suffix_value = str(getattr(suffix_node, "value", "")).strip().lower()
    if suffix_value in TRUTHY:
        # `name: switchboard` + name_add_mac_suffix -> children are
        # `switchboard-aabbcc`, so the bare name is the family prefix.
        prefix = declared if isinstance(declared, str) and declared else None
        return Classification(True, "mac-suffix-flag", directives, prefix)

    return Classification(False, "default", directives)


def _name_prefix_of(raw: str, path: Path | None) -> str | None:
    """``esphome.name``'s literal prefix, for an explicitly marked parent."""
    try:
        root = yc.compose(raw)
    except yc.YamlParseError:
        return None
    if root is None:
        return None
    name_node = yc.map_get_path(root, "esphome", "name")
    declared = getattr(name_node, "value", None)
    if not isinstance(declared, str) or not declared:
        return None
    return derive_name_prefix(declared) or declared
