"""Generation fidelity: preserve everything, change only what must change.

The strictest tests here assert the *exact* set of changed lines. That is
deliberate -- a generator that quietly reformats an unrelated part of someone's
firmware config is worse than one that fails loudly, so any unintended edit
should break the build.
"""

from __future__ import annotations

import difflib
from pathlib import Path

import pytest

from app.generator import YamlGenerator
from app.models import Device, DeviceStatus, MacPolicy, MacSuffixAction, TemplateSpec
from app.yaml_compat import YamlParseError, load


def template(raw: str, **kwargs) -> TemplateSpec:
    return TemplateSpec(name="t.yaml", path=Path("t.yaml"), raw=raw, **kwargs)


def strip_header(content: str) -> str:
    """Drop the generated provenance block so a diff shows only real edits."""
    marker = "# Generated by ESPHome Device Scan"
    if not content.startswith(marker):
        return content
    # The header is a run of comment lines terminated by one blank line.
    _, _, rest = content.partition("\n\n")
    return rest


def changed_lines(before: str, after: str) -> tuple[list[str], list[str]]:
    """Lines removed from and added to the template body."""
    removed, added = [], []
    for line in difflib.unified_diff(
        before.splitlines(), strip_header(after).splitlines(), lineterm="", n=0
    ):
        if line[:3] in ("---", "+++", "@@ ") or line.startswith("@@"):
            continue
        if line.startswith("-"):
            removed.append(line[1:])
        elif line.startswith("+"):
            added.append(line[1:])
    return removed, added


# -- preservation -----------------------------------------------------------


def test_only_the_intended_lines_change(cloudbay_template, device, generator) -> None:
    out = generator.generate(cloudbay_template, device)
    removed, added = changed_lines(cloudbay_template.raw, out.content)

    assert sorted(removed) == sorted([
        "  devicename: cloudbay-t",
        '  mac: "000000"',
        "  name: cloudbay-t-${mac}",
        '  friendly_name: "${friendly} ${mac}"',
        "  name_add_mac_suffix: true",
    ])
    assert sorted(added) == sorted([
        "  devicename: cloudbay-t-livingroom",
        '  mac: "ddeeff"',
        "  name: cloudbay-t-livingroom",
        '  friendly_name: "CloudBay T Living Room"',
        "  name_add_mac_suffix: false",
    ])


def test_comments_survive(cloudbay_template, device, generator) -> None:
    out = generator.generate(cloudbay_template, device)
    assert "# CloudBay T -- base firmware template" in out.content
    assert "# Fallback hotspot, used when the configured network is unreachable." in out.content


def test_secret_tags_survive(cloudbay_template, device, generator) -> None:
    out = generator.generate(cloudbay_template, device)
    for secret in (
        "!secret api_encryption_key",
        "!secret ota_password",
        "!secret wifi_ssid",
        "!secret ap_password",
    ):
        assert secret in out.content


def test_key_order_and_blank_lines_survive(cloudbay_template, device, generator) -> None:
    out = generator.generate(cloudbay_template, device)
    keys = [
        line.split(":")[0]
        for line in out.content.splitlines()
        if line and not line.startswith(("#", " ")) and ":" in line
    ]
    assert keys == [
        "substitutions", "esphome", "esp32", "logger", "api", "ota",
        "wifi", "captive_portal", "sensor", "binary_sensor", "button",
    ]
    assert "\n\ncaptive_portal:\n" in out.content


def test_nested_structures_are_untouched(cloudbay_template, device, generator) -> None:
    out = generator.generate(cloudbay_template, device)
    assert "  on_boot:\n    priority: 600\n" in out.content
    assert "    - logger.log: \"CloudBay T booted\"" in out.content
    assert "  framework:\n    type: esp-idf\n" in out.content


def test_output_is_still_valid_yaml(cloudbay_template, device, generator) -> None:
    out = generator.generate(cloudbay_template, device)
    data = load(out.content)
    assert data["esphome"]["name"] == "cloudbay-t-livingroom"
    assert data["esphome"]["name_add_mac_suffix"] is False


def test_block_scalars_are_left_alone(generator, device) -> None:
    raw = (
        "esphome:\n  name: x\n"
        "  on_boot:\n    then:\n      - lambda: |-\n"
        '          ESP_LOGD("tag", "${mac}");\n'
    )
    out = generator.generate(template(raw), device)
    assert '${mac}' in out.content  # inside a lambda: not ours to rewrite


def test_anchors_and_aliases_are_not_corrupted(generator, device) -> None:
    """A value reached by alias reports its *anchor's* offsets; never patch it."""
    raw = (
        "defaults: &common\n  name: anchored\n"
        "esphome:\n  name: cloudbay-t-${mac}\n"
        "other: *common\n"
    )
    out = generator.generate(template(raw), device)

    assert "defaults: &common\n  name: anchored\n" in out.content
    assert "other: *common" in out.content
    assert "  name: cloudbay-t-livingroom" in out.content


# -- determinism and idempotency -------------------------------------------


def test_generation_is_deterministic(cloudbay_template, device, generator) -> None:
    outputs = {generator.generate(cloudbay_template, device).content for _ in range(5)}
    assert len(outputs) == 1


def test_two_generator_instances_agree(cloudbay_template, device) -> None:
    a = YamlGenerator(MacPolicy.SUFFIX3, MacSuffixAction.SET_FALSE)
    b = YamlGenerator(MacPolicy.SUFFIX3, MacSuffixAction.SET_FALSE)
    assert a.generate(cloudbay_template, device).content == b.generate(
        cloudbay_template, device
    ).content


def test_header_carries_no_timestamp(cloudbay_template, device, generator) -> None:
    """A clock reading in the header would break idempotency on every rerun."""
    import re

    out = generator.generate(cloudbay_template, device)
    header = out.content.split("\n\n")[0]
    assert not re.search(r"\d{4}-\d{2}-\d{2}", header)
    assert not re.search(r"\d{2}:\d{2}:\d{2}", header)


def test_regenerating_from_output_is_stable(cloudbay_template, device, generator) -> None:
    """Feeding a generated file back in must not accumulate changes."""
    first = generator.generate(cloudbay_template, device).content
    second = generator.generate(
        template(first), device
    ).content
    # Only the provenance header is prepended a second time; the config body
    # below it must be byte-identical.
    assert second.endswith(first[first.index("substitutions:") :])


# -- header -----------------------------------------------------------------


def test_header_names_the_template_and_device(cloudbay_template, device, generator) -> None:
    out = generator.generate(cloudbay_template, device)
    assert out.content.startswith("# Generated by ESPHome Device Scan")
    assert "# Template: cloudbay-t.yaml" in out.content
    assert "# Device:   cloudbay-t-livingroom" in out.content
    assert "# MAC:      AA:BB:CC:DD:EE:FF" in out.content


def test_header_can_be_disabled(cloudbay_template, device) -> None:
    gen = YamlGenerator(add_header=False)
    assert not gen.generate(cloudbay_template, device).content.startswith("#" " Generated")


def test_document_marker_stays_first(generator, device) -> None:
    out = generator.generate(template("---\nesphome:\n  name: x\n"), device)
    assert out.content.startswith("---\n# Generated by ESPHome Device Scan")


def test_output_always_ends_with_a_newline(generator, device) -> None:
    out = generator.generate(template("esphome:\n  name: x"), device)
    assert out.content.endswith("\n")


# -- error handling ---------------------------------------------------------


def test_malformed_template_raises_a_clear_error(generator, device) -> None:
    with pytest.raises(YamlParseError):
        generator.generate(template("esphome:\n  name: [unclosed\n"), device)


def test_empty_template_raises(generator, device) -> None:
    with pytest.raises(YamlParseError, match="empty"):
        generator.generate(template("# just a comment\n"), device)


def test_template_without_an_esphome_block_warns(generator, device) -> None:
    out = generator.generate(template("logger:\n  level: INFO\n"), device)
    assert any("no 'esphome:' block" in w for w in out.warnings)
    assert "logger:" in out.content


def test_template_without_a_name_key_warns(generator, device) -> None:
    out = generator.generate(template("esphome:\n  friendly_name: Thing\n"), device)
    assert any("no 'name:' key" in w for w in out.warnings)


def test_switchboard_template_round_trip(switchboard_template, generator) -> None:
    device = Device(
        node_name="switchboard-hallway", mac="112233445566", status=DeviceStatus.ONLINE
    )
    out = generator.generate(switchboard_template, device)

    assert "name: switchboard-hallway" in out.content
    assert "name_add_mac_suffix: false" in out.content
    assert 'ssid: "Switchboard Fallback"' in out.content  # untouched
    assert out.content.count("platform: gpio") == 4
    assert load(out.content)["esphome"]["name"] == "switchboard-hallway"
